# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/denisenk/raskroy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/denisenk/raskroy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/denisenk/raskroy/CMakeFiles /home/denisenk/raskroy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/denisenk/raskroy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named guillotine_interop

# Build rule for target.
guillotine_interop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 guillotine_interop
.PHONY : guillotine_interop

# fast build rule for target.
guillotine_interop/fast:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/build
.PHONY : guillotine_interop/fast

guillotine_interop.o: guillotine_interop.cpp.o
.PHONY : guillotine_interop.o

# target to build an object file
guillotine_interop.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/guillotine_interop.cpp.o
.PHONY : guillotine_interop.cpp.o

guillotine_interop.i: guillotine_interop.cpp.i
.PHONY : guillotine_interop.i

# target to preprocess a source file
guillotine_interop.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/guillotine_interop.cpp.i
.PHONY : guillotine_interop.cpp.i

guillotine_interop.s: guillotine_interop.cpp.s
.PHONY : guillotine_interop.s

# target to generate assembly for a file
guillotine_interop.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/guillotine_interop.cpp.s
.PHONY : guillotine_interop.cpp.s

layout1d.o: layout1d.cpp.o
.PHONY : layout1d.o

# target to build an object file
layout1d.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout1d.cpp.o
.PHONY : layout1d.cpp.o

layout1d.i: layout1d.cpp.i
.PHONY : layout1d.i

# target to preprocess a source file
layout1d.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout1d.cpp.i
.PHONY : layout1d.cpp.i

layout1d.s: layout1d.cpp.s
.PHONY : layout1d.s

# target to generate assembly for a file
layout1d.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout1d.cpp.s
.PHONY : layout1d.cpp.s

layout2d.o: layout2d.cpp.o
.PHONY : layout2d.o

# target to build an object file
layout2d.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout2d.cpp.o
.PHONY : layout2d.cpp.o

layout2d.i: layout2d.cpp.i
.PHONY : layout2d.i

# target to preprocess a source file
layout2d.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout2d.cpp.i
.PHONY : layout2d.cpp.i

layout2d.s: layout2d.cpp.s
.PHONY : layout2d.s

# target to generate assembly for a file
layout2d.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/layout2d.cpp.s
.PHONY : layout2d.cpp.s

raskroy.o: raskroy.cpp.o
.PHONY : raskroy.o

# target to build an object file
raskroy.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/raskroy.cpp.o
.PHONY : raskroy.cpp.o

raskroy.i: raskroy.cpp.i
.PHONY : raskroy.i

# target to preprocess a source file
raskroy.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/raskroy.cpp.i
.PHONY : raskroy.cpp.i

raskroy.s: raskroy.cpp.s
.PHONY : raskroy.s

# target to generate assembly for a file
raskroy.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/raskroy.cpp.s
.PHONY : raskroy.cpp.s

result.o: result.cpp.o
.PHONY : result.o

# target to build an object file
result.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/result.cpp.o
.PHONY : result.cpp.o

result.i: result.cpp.i
.PHONY : result.i

# target to preprocess a source file
result.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/result.cpp.i
.PHONY : result.cpp.i

result.s: result.cpp.s
.PHONY : result.s

# target to generate assembly for a file
result.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/result.cpp.s
.PHONY : result.cpp.s

types.o: types.cpp.o
.PHONY : types.o

# target to build an object file
types.cpp.o:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/types.cpp.o
.PHONY : types.cpp.o

types.i: types.cpp.i
.PHONY : types.i

# target to preprocess a source file
types.cpp.i:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/types.cpp.i
.PHONY : types.cpp.i

types.s: types.cpp.s
.PHONY : types.s

# target to generate assembly for a file
types.cpp.s:
	$(MAKE) -f CMakeFiles/guillotine_interop.dir/build.make CMakeFiles/guillotine_interop.dir/types.cpp.s
.PHONY : types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... guillotine_interop"
	@echo "... rebuild_cache"
	@echo "... guillotine_interop.o"
	@echo "... guillotine_interop.i"
	@echo "... guillotine_interop.s"
	@echo "... layout1d.o"
	@echo "... layout1d.i"
	@echo "... layout1d.s"
	@echo "... layout2d.o"
	@echo "... layout2d.i"
	@echo "... layout2d.s"
	@echo "... raskroy.o"
	@echo "... raskroy.i"
	@echo "... raskroy.s"
	@echo "... result.o"
	@echo "... result.i"
	@echo "... result.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

