//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denisenko.Cutting.CutOptima {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Denisenko.Cutting.CutOptima.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before running layout you should save changes. Save changes?.
        /// </summary>
        internal static string BeforeRunningLayoutShouldSaveChanges {
            get {
                return ResourceManager.GetString("BeforeRunningLayoutShouldSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove database from the list? The actual database files will not be deleted..
        /// </summary>
        internal static string ConfirmRemoveDatabase {
            get {
                return ResourceManager.GetString("ConfirmRemoveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the database server.
        /// </summary>
        internal static string ConnectingToTheDatabaseServer {
            get {
                return ResourceManager.GetString("ConnectingToTheDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the database server.
        /// </summary>
        internal static string CouldntConnectToTheDatabaseServer {
            get {
                return ResourceManager.GetString("CouldntConnectToTheDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create database.
        /// </summary>
        internal static string CouldntCreateDatabase {
            get {
                return ResourceManager.GetString("CouldntCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create database schema.
        /// </summary>
        internal static string CouldntCreateDatabaseSchema {
            get {
                return ResourceManager.GetString("CouldntCreateDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t switch to database.
        /// </summary>
        internal static string CouldntSwitchToDatabase {
            get {
                return ResourceManager.GetString("CouldntSwitchToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database.
        /// </summary>
        internal static string CreatingDatabase {
            get {
                return ResourceManager.GetString("CreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database created successufully.
        /// </summary>
        internal static string DatabaseCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DatabaseCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is being created.
        /// </summary>
        internal static string DatabaseIsBeingCreated {
            get {
                return ResourceManager.GetString("DatabaseIsBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database with such parameters already present.
        /// </summary>
        internal static string DatabaseWithSuchParametersAlreadyPresent {
            get {
                return ResourceManager.GetString("DatabaseWithSuchParametersAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout: {0}  size: {1:0.0} x {2:0.0}  material: {3}.
        /// </summary>
        internal static string LayoutTitleFormat {
            get {
                return ResourceManager.GetString("LayoutTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Parts List.
        /// </summary>
        internal static string NewPartsList {
            get {
                return ResourceManager.GetString("NewPartsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts List.
        /// </summary>
        internal static string PartsList {
            get {
                return ResourceManager.GetString("PartsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
